#ifndef SHARED_H
#define SHARED_H

#define TEMPERATURES_SENSOR_INTERVAL 2000
#define VELOCITY_SENSOR_INTERVAL 10000
#define DIRECTION_SENSOR_INTERVAL 10000
#define PLUVIO_SENSOR_INTERVAL 10000
#define SOIL_HUMIDITY_SENSOR_INTERVAL 10000
#define AIR_HUMIDITY_SENSOR_INTERVAL 10000

extern const char TEMP_SENSOR_MAX_VARIATION;
extern const char TEMP_BASE_VALUE;
extern const char VELC_SENSOR_MAX_VARIATION;
extern const char PLUV_CONTRIB_HUMD;
extern const char SOIL_HUMD_SENSOR_MAX_VARIATION;
extern const char SOIL_HUMD_SENSOR_RAINING_MAX_VARIATION;
extern const char VELC_SENSOR_DIR_WIND_MAX_VARIATION;
extern const char PLUVIO_SENSOR_MAX_VARIATION;
extern const char HIGH_TEMP_DEFAULT;
extern const char PLUVIO_SENSOR_MAX_VARIATION_HIGH_TEMP;

#define N_OF_TEMP_SENSORS 3
#define N_OF_VELOCITY_SENSORS 3
#define N_OF_DIRECTION_SENSORS 3
#define N_OF_PLUVIO_SENSORS 3
#define N_OF_SOIL_HUMIDITY_SENSORS 3
#define N_OF_AIR_HUMIDITY_SENSORS 3

#define TEMPERATURE_SENSORS_INDEX 0
#define VELOCITY_SENSORS_INDEX 1
#define DIR_WIND_SENSORS_INDEX 2
#define PLUVIO_SENSORS_INDEX 3
#define SOIL_HUMIDITY_SENSORS_INDEX 4
#define AIR_HUMIDITY_SENSORS_INDEX 5

#define SEC_IN_DAY 86400

#define NUM_TEMPERATURE_REGISTERS SEC_IN_DAY / TEMPERATURES_SENSOR_INTERVAL
#define NUM_VEL_WIND_REGISTERS SEC_IN_DAY / VELOCITY_SENSOR_INTERVAL
#define NUM_DIR_WIND_REGISTERS SEC_IN_DAY / DIRECTION_SENSOR_INTERVAL
#define NUM_PLUVIO_REGISTERS SEC_IN_DAY / PLUVIO_SENSOR_INTERVAL
#define NUM_SOIL_HUMIDITY_REGISTERS SEC_IN_DAY / SOIL_HUMIDITY_SENSOR_INTERVAL
#define NUM_AIR_HUMIDITY_REGISTERS SEC_IN_DAY / AIR_HUMIDITY_SENSOR_INTERVAL

#define TEMPERATURE_SENSOR_TYPE 0
#define VELOCITY_SENSOR_TYPE 1
#define DIRECTION_SENSOR_TYPE 2
#define PLUVIO_SENSOR_TYPE 3
#define SOIL_HUMIDITY_SENSOR_TYPE 4
#define AIR_HUMIDITY_SENSOR_TYPE 5

#define NUM_OF_SENSORS 6

#endif

