#ifndef SHARED_H
#define SHARED_H

#define NUM_OF_SENSOR_TYPES 6

enum sensor_types {
    TEMPERATURE_SENSOR_TYPE,
    WIND_VELOCITY_SENSOR_TYPE,
    WIND_DIRECTION_SENSOR_TYPE,
    PLUVIO_SENSOR_TYPE,
    SOIL_HUMIDITY_SENSOR_TYPE,
    AIR_HUMIDITY_SENSOR_TYPE
};

// #define TEST sizeof(int) // this is possible

#define SEC_IN_DAY 86400

// Default frequency for each sensor type
#define TEMPERATURES_SENSOR_INTERVAL 2000
#define WIND_VELOCITY_SENSOR_INTERVAL 10000
#define WIND_DIRECTION_SENSOR_INTERVAL 10000
#define PLUVIO_SENSOR_INTERVAL 10000
#define SOIL_HUMIDITY_SENSOR_INTERVAL 10000
#define AIR_HUMIDITY_SENSOR_INTERVAL 10000

// Default readings size
#define NUM_TEMPERATURE_REGISTERS SEC_IN_DAY / TEMPERATURES_SENSOR_INTERVAL
#define NUM_WIND_VELOCITY_REGISTERS SEC_IN_DAY / WIND_VELOCITY_SENSOR_INTERVAL
#define NUM_WIND_DIRECTION_REGISTERS SEC_IN_DAY / WIND_DIRECTION_SENSOR_INTERVAL
#define NUM_PLUVIO_REGISTERS SEC_IN_DAY / PLUVIO_SENSOR_INTERVAL
#define NUM_SOIL_HUMIDITY_REGISTERS SEC_IN_DAY / SOIL_HUMIDITY_SENSOR_INTERVAL
#define NUM_AIR_HUMIDITY_REGISTERS SEC_IN_DAY / AIR_HUMIDITY_SENSOR_INTERVAL

// shared.c
extern const char TEMP_SENSOR_MAX_VARIATION;
extern const char TEMP_BASE_VALUE;
extern const char VELC_SENSOR_MAX_VARIATION;
extern const char PLUV_CONTRIB_HUMD;
extern const char SOIL_HUMD_SENSOR_MAX_VARIATION;
extern const char SOIL_HUMD_SENSOR_RAINING_MAX_VARIATION;
extern const char VELC_SENSOR_DIR_WIND_MAX_VARIATION;
extern const char PLUVIO_SENSOR_MAX_VARIATION;
extern const char HIGH_TEMP_DEFAULT;
extern const char PLUVIO_SENSOR_MAX_VARIATION_HIGH_TEMP;

// LIMITS
#define UPPER_LIMIT_TEMPERATURE 25
#define LOWER_LIMIT_TEMPERATURE 0
#define UPPER_LIMIT_WIND_VELOCITY 50
#define LOWER_LIMIT_WIND_VELOCITY 0
#define UPPER_LIMIT_WIND_DIRECTION 359
#define LOWER_LIMIT_WIND_DIRECTION 0
#define UPPER_LIMIT_PLUVIO 30
#define LOWER_LIMIT_PLUVIO 0
#define UPPER_LIMIT_SOIL_HUMIDITY 100
#define LOWER_LIMIT_SOIL_HUMIDITY 0
#define UPPER_LIMIT_AIR_HUMIDITY 100
#define LOWER_LIMIT_AIR_HUMIDITY 0

#define MAX_INCORRECT_READS 3
// END OF LIMITS

#endif

